# Generated by Django 4.2.2 on 2023-07-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_year', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('prog_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('prog_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['prog_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.CharField(max_length=12, unique=True)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('othernames', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('national_id', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField(null=True, unique=True)),
                ('image', models.FileField(upload_to='uploads')),
                ('prog_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Students.program')),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('sem', models.CharField(max_length=15, unique=True)),
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.academic_year')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_desc', models.TextField()),
                ('prog_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.program')),
            ],
        ),
    ]
