# Generated by Django 4.2.2 on 2023-07-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Students.academic_year'),
            preserve_default=False,
        ),
    ]
