# Generated by Django 4.2.2 on 2023-07-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_course_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Students.academic_year'),
            preserve_default=False,
        ),
    ]
