# Generated by Django 4.2.2 on 2023-07-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_sem_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem',
            name='academic_year',
        ),
    ]
