# Generated by Django 4.2.2 on 2023-07-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_remove_sem_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
