# Generated by Django 4.2.2 on 2023-07-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='ac_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.academic_year'),
        ),
    ]
