# Generated by Django 4.2.2 on 2023-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_remove_semester_ac_year_course_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='fac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
