# Generated by Django 4.2.2 on 2023-10-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_program_fac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='fac',
            new_name='faculty',
        ),
    ]
