# Generated by Django 4.2.2 on 2023-10-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_faculty_fac_code'),
        ('Students', '0009_rename_fac_program_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.faculty'),
        ),
    ]
