# Generated by Django 4.2.4 on 2023-10-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True),
        ),
    ]
