# Generated by Django 4.2.2 on 2023-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_year',
            name='status',
            field=models.CharField(default='inactive', max_length=7),
        ),
    ]
