# Generated by Django 4.2.2 on 2023-10-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_academic_year_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.sem')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.academic_year')),
            ],
        ),
    ]
