# Generated by Django 4.2.2 on 2023-10-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0014_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('year', 'semester', 'student')},
        ),
    ]
