# Generated by Django 4.2.2 on 2023-10-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0016_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='year',
            new_name='academic_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Academic_year',
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Students.year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='Academic_year',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('academic_year', 'semester', 'student')},
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
