# Generated by Django 4.2.2 on 2023-10-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0017_rename_year_session_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
    ]
