# Generated by Django 4.2.4 on 2023-10-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_student_year_of_study'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session1',
        ),
    ]
