# Generated by Django 4.2.2 on 2023-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_ID', models.TextField(max_length=30)),
                ('ResultDesc', models.TextField(max_length=50)),
                ('CheckOutID', models.TextField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
