# Generated by Django 4.2.2 on 2023-07-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
