# Generated by Django 4.2.2 on 2023-07-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lipa', '0002_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Checkout_id', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=30)),
                ('date_transacted', models.DateTimeField()),
                ('completed', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
