# Generated by Django 4.2.2 on 2023-07-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipa', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
