# Generated by Django 4.2.2 on 2023-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=12)),
                ('subjects', models.TextField(max_length=300)),
                ('hobbies', models.TextField(max_length=200)),
            ],
        ),
    ]
