# Generated by Django 4.2.2 on 2023-02-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_no', models.CharField(max_length=12, unique=True)),
                ('surname', models.CharField(max_length=20)),
                ('othernames', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='staffs')),
            ],
        ),
        migrations.DeleteModel(
            name='Lecturers',
        ),
    ]
