# Generated by Django 4.2.2 on 2023-08-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_lecturer_delete_lecturers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_code', models.CharField(max_length=10)),
                ('fac_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_code', models.CharField(max_length=20, unique=True)),
                ('dep_name', models.CharField(max_length=50, unique=True)),
                ('fac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.faculty')),
            ],
        ),
    ]
