# Generated by Django 4.2.2 on 2023-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_name',
            field=models.CharField(max_length=60),
        ),
    ]
