# Generated by Django 4.2.2 on 2023-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_faculty_fac_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
