# Generated by Django 4.2.2 on 2023-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
