# Generated by Django 4.2.2 on 2023-10-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_admission'),
        ('staffs', '0005_alter_faculty_fac_code'),
        ('academia', '0004_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_description', models.TextField()),
                ('year', models.IntegerField()),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.program')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('class_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.classr')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.lecturer')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
